### ISSUE TITLE
[BUG] Short description of the bug

### ISSUE THREAD

**Issue by CuteWaterBeary** [mnaoumov/obsidian-dev-utils#2]
### Description

When trying to compile obsidian-custom-attachment-location this plugin causes an error:

Error: An error occurred during task execution
Error stack:
    at wrapResult (/Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/scripts/CliUtils.cjs:141:34)
    at async wrapCliTask (/Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/scripts/CliUtils.cjs:146:18)
    at async addErrorHandler (/Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/Async.cjs:90:5)
Caused by:
Error: Could not find root directory
Error stack:
    at getRootDir (/Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/scripts/Root.cjs:61:9)
    at resolvePathFromRoot (/Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/scripts/Root.cjs:51:35)
    at getPackageJsonPath (/Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/scripts/Npm.cjs:68:46)
    at readNpmPackage (/Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/scripts/Npm.cjs:42:42)
    at /Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/scripts/cli.cjs:60:60
    at wrapResult (/Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/scripts/CliUtils.cjs:139:18)
    at wrapCliTask (/Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/scripts/CliUtils.cjs:146:24)
    at /Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/scripts/cli.cjs:59:77
    at addErrorHandler (/Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/Async.cjs:90:11)
    at invokeAsyncSafely (/Users/WaterBeary/Vault/.obsidian/plugins/obsidian-custom-attachment-location/node_modules/obsidian-dev-utils/dist/lib/Async.cjs:86:8)

### Steps to Reproduce

2. Click on '...'
3. Notice that '...'
...
npm install
npm run build

### Expected Behavior

For it to compile like other plugins

### Actual Behavior

Error message

### Environment Information

- **obsidian-dev-utils Version**: [obsidian-custom-attachment-location version and the latest 4.7 version]
- **Operating System**: [Mac]

### Attachments

- Please attach a video showing the issue
No

### Confirmations

- [X] I attached a video showing the issue
- [X] I have tested the issue with the latest version
- [X] I have checked for existing issues

**Comment by mnaoumov** [comment]
@CuteWaterBeary please add all the required details

**Comment by CuteWaterBeary** [comment]
I was able to remove your dependency and went back to using a esbuild.config.mjs file instead and now it works

**Comment by mnaoumov** [comment]
@CuteWaterBeary if this works for you better, sure
